export const CUSTOM_CONFIG_SERVICE = Symbol('CUSTOM_CONFIG_SERVICE');
export const CUSTOM_CONFIGURATION_TOKEN = 'CUSTOM_CONFIGURATION_TOKEN';
export const CUSTOM_CONFIGURATION_LOADER = 'CUSTOM_CONFIGURATION_LOADER';
export const PARTIAL_CUSTOM_CONFIGURATION_KEY = 'PARTIAL_CUSTOM_CONFIGURATION_KEY';
